[package]
name = "trace-rs"
version = "0.1.0"
authors = ["Trond H Emaus <trondhe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.21.0"
rand = "0.7.3"